# Generated by Django 2.1.2 on 2018-12-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscodes',
            name='CodeNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='accesscodes',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='CardNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='SecurityNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='Zipcode',
            field=models.IntegerField(),
        ),
    ]
