# Generated by Django 2.1.2 on 2018-12-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20181203_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscodes',
            name='Price',
        ),
        migrations.AlterField(
            model_name='accesscodes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
